name: ericgardner.info
title: "Eric Gardner"
email: gardner.ec@gmail.com
description: "Graphic design, web development, and art direction."
baseurl: ""
url: "http://ericgardner.info"

twitter_username: ecgardner
github_username:  egardner

markdown: redcarpet
highlighter: pygments
