name: ericgardner.info
title: "Eric Gardner"
email: gardner.ec@gmail.com
description: "Los Angeles, CA<br />Art direction + graphic design"
baseurl: ""
url: "http://ericgardner.info"

twitter_username: ecgardner
github_username:  egardner

markdown: redcarpet
highlighter: pygments
